export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const RESTORE_PASSWORD = 'RESTORE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';
export const ACTIVATE_ACCOUNT = "ACTIVATE_ACCOUNT";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SEARCH_USER_BY_EMAIL = 'SEARCH_USER_BY_EMAIL';
export const CLEAN_FILTER_USER_BY_EMAIL = 'CLEAN_FILTER_USER_BY_EMAIL';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

/* Types para Egresos - Ingresos */
export const CREATE_EXPENSE = 'CREATE_EXPENSE';
export const CREATE_INCOME = 'CREATE_INCOME';

/* Types para sucursales */
export const GET_SUBOFFICES = 'GET_SUBOFFICES';
export const DELETE_CURRENCY_SUBOFFICES = 'DELETE_CURRENCY_SUBOFFICES';
export const UPDATE_CURRENCY_SUBOFFICES = 'UPDATE_CURRENCY_SUBOFFICES';

/* Types para currencies */
export const CREATE_CURRENCIES = 'CREATE_CURRENCIES';
export const GET_CURRENCIES = 'GET_CURRENCIES'
export const DELETE_CURRENCY = 'DELETE_CURRENCY';

/* Types para la apertura-cierre de caja */
export const OPEN_CASH_REGISTER = 'OPEN_CASH_REGISTER';
export const CLOSE_CASH_REGISTER = 'CLOSE_CASH_REGISTER';
export const VERIFY_CASH_REGISTER = 'VERIFY_CASH_REGISTER';
export const VERIFY_CASH_REGISTER_ERROR = 'VERIFY_CASH_REGISTER_ERROR';
export const CLEAR_CASH_REGISTER_ERROR = "CLEAR_CASH_REGISTER_ERROR";